export const FETCH_EVENTS_REQUEST = 'FETCH_EVENTS_REQUES'
export const FETCH_EVENTS_SUCCES = 'FETCH_EVENTS_SUCCES'
export const FETCH_EVENTS_FAIL = 'FETCH_EVENTS_SUCCES_FAIL'

export const EVENT_CREATE_REQUEST = 'EVENT_CREATE_REQUEST'
export const EVENT_CREATE_SUCCESS = 'EVENT_CREATE_SUCCESS'
export const EVENT_CREATE_FAIL = 'EVENT_CREATE_FAIL'

export const EVENT_EDIT_REQUEST = 'EVENT_EDIT_REQUEST'
export const EVENT_EDIT_SUCCESS = 'EVENT_EDIT_SUCCESS'
export const EVENT_EDIT_FAIL = 'EVENT_EDIT_FAIL'

export const EVENT_DELETE_REQUEST = 'EVENT_DELETE_REQUEST'
export const EVENT_DELETE_SUCCESS = 'EVENT_DELETE_SUCCESS'
export const EVENT_DELETE_FAIL = 'EVENT_DELETE_FAIL'
